### ISSUE TITLE
[QUESTION] Availability of trained models

### ISSUE THREAD

**Issue by Lhemamou** [pliang279/MultiBench#18]
Hello everyone :)

First congratulations for this amazing work and benchmark ! It's really really huge ! Second, i was wondering if some already trained models could potentially be shared (e.g. best state of the art, specific to some domains , etc)

Again a huge congrats !!

Léo

**Comment by lvyiwei1** [comment]
Hi Leo,
     Thank you for your interest in our works! Unfortunately we did not save the checkpoints to our trained models. However, we do provide the scripts (and hyperparameters) in the repo to directly train the models, and most of them train pretty fast, so you can train the models with our scripts.
     Hope that helps!
-Yiwei
