### ISSUE TITLE
Code to obtain features from raw data

### ISSUE THREAD

**Issue by srb-cv** [pliang279/MultiBench#24]
Could you please tell us if scripts are available to obtain features from the raw video and audio data? Could you point us to the code or provide us with the code?

**Comment by Vanvan2017** [comment]
Hey, you can refer to [OpenFace](https://github.com/TadasBaltrusaitis/OpenFace) and [Facet](https://imotions.com/), note that Facet is a commercial tool. So sorry that these features are processed years ago thus it is hard to find the script, if you need all the features you can use the [MultimodalSDK](https://github.com/A2Zadeh/CMU-MultimodalSDK), but if you want to deal with some new dataset created by yourself, I think you can try some state-of-the-art method for video and audio especially some fine-tuning ways as you said in the last issue!
