### ISSUE TITLE
Questions about the im.pk data & MFM

### ISSUE THREAD

**Issue by wccch** [pliang279/MultiBench#37]
How exactly are the im.pk files used in healthcare examples obtained and pre-processed? For example, what is the specific content of the label in the im.pk file, what is the specific data of the two modes in the im.pk file, and what data is recorded?
Finally, I would like to ask what is the specific MFM method mentioned and used in the project, and what is the full name of MFM?
I would really appreciate your reply! As I have been preparing my project recently, the multibench subject has helped me a lot!

**Comment by lvyiwei1** [comment]
Hi wccch, for details about how we processed MIMIC-III to obtain im.pk, please refer to Appendix C.2.2 in our paper The data in the two modes are the 5 static features and 12 timeseries features from feature set A of Purushotham et al (see reference [129] in our paper). MFM stands for Multimodal Factorized Model (see reference [155] in our paper). Hope this helps!

**Comment by wccch** [comment]
Thanks for your prompt reply！
