### ISSUE TITLE
Question about the mortality label on im.pk file

### ISSUE THREAD

**Issue by wccch** [pliang279/MultiBench#38]
First, thanks for replying to my last question. But I still have a few questions about the im.pk file mortality lables. According to the paper, there are six labels that correspond to six different times of death. So shouldn't only one of these six labels be 1? But when I was debugging, I found that the lables for different time of death sometimes equal 1 at the same time. So I think there is some deviation in my understanding, please give me some guidance.Thank you！

**Comment by wccch** [comment]
![Uploading lables.png…]()

**Comment by wccch** [comment]
![Uploading lables.png…]()

**Comment by wccch** [comment]
![lables](https://github.com/pliang279/MultiBench/assets/111749526/a5457768-0734-49b7-b75e-e6ca9d2598a1)

**Comment by lvyiwei1** [comment]
The only useful labels are the columns 1-5, where a 1 in each column indicates whether the patient has died within a certain range of time, ranged from short to long ( 1 day, 2 day, 3 day, 1 week, 1 year respectively). Therefore, the corresponding 6 classes are death within 1 day, between 1 and 2 day, between 2 and 3 day, between 3 day and 1 week, between 3 week and 1 year, and still alive after 1 year. You may refer to line 62-74 from `datasets/mimic/get_data.py` for how the above binary labels are processed to 6-way multi-class mortality labels
