### ISSUE TITLE
The Kinetics Dataset

### ISSUE THREAD

**Issue by duchenzhuang** [pliang279/MultiBench#4]
Where can I get the data in /data/yiwei/kinetics?

**Comment by duchenzhuang** [comment]
Now I have downloaded the kinetics400 dataset. And the data is organized like this: /kinetics/train/class_name/*.mp4, /kinetics/val/class_name/*.mp4. How can I process the data to get ".pdt" file?

**Comment by lvyiwei1** [comment]
Hello, sorry for the late reply. You can see an example of processing mp4 files into .pt files in datasets/kinetics/getkineticssmall.py, and then you can find examples of merging the .pt files into .pdt files in datasets/kinetics/tobatch_37.py. Hope this helps!
